services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
    healthCheckPath: /health
    
databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user